### ISSUE TITLE
How can I update the updateservice-sample-pull-secret to include credentials not available in the cluster by default?

### ISSUE THREAD

**Issue by benemon** [openshift/cincinnati-operator#123]
The pull secret is managed by the OpenShift Update Service operator. Changes made directly to the pull secret are overridden. How can I add additional credentials or supply a different pull secret to the Operator?

**Comment by benemon** [comment]
Thanks, openshift-bot.

**Comment by Goose29** [comment]
OSUS will use the secret named `pull-secret` in the openshift-config namespace, this can be created or patched with additional auths like this:

````
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: openshift-config
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |-
        {
            "auths": {
                "my-auth": {
                    "auth": "username:password"
                }
	    }
	}
```
