### ISSUE TITLE
No matches for kind PodDisruptionBudget in OKD 4.12

### ISSUE THREAD

**Issue by Goose29** [openshift/cincinnati-operator#160]
When running openshift-update-service v5.0.0 (cincinnati-operator) on the latest OKD 4.12 release, installed through "registry.redhat.io/redhat/redhat-operator-index:v4.12" catalogsource.

I get the following error:

```
ERROR	cmd	Manager exited non-zero	{"error": "no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\""}
```

https://catalog.redhat.com/software/operators/detail/5f0f35842991b4207fcdb202 - Here it is stated that 4.12 is supported; Is there api differences between OCP 4.12 & OKD 4.12 that could cause this?

**Comment by PratikMahajan** [comment]
fixed in #154

**Comment by Goose29** [comment]
@PratikMahajan when is the release planned for?

**Comment by trotro** [comment]
> We'll be releasing v5.0.1 soon with this fix

Do you have any ETA for this new release ? I see only v5.0.0 in the catalog.

And looks like you're not using release tags anymore. The last one is v1.0.3 from Aug 26, 2020. This is kind of confusing regarding the versions on the catalog, imho.
